### ISSUE TITLE
Compatibility Issues when running Easy SEO and Yoast SEO

### ISSUE THREAD

**Issue by boldgrid-support** [BoldGrid/post-and-page-builder#59] opened 2018-12-18 20:19 UTC
**Description**
Drag handles and Add Block functionality do not work correctly when Yoast SEO and Easy SEO are both activated.  This started happening with WordPress 5.0.1 core update.

**Replication**
1. Install/Activate Post and Page Builder, Easy SEO, and Yoast SEO.
2. Edit a Page or Post.
3. Drag handles should not appear on hover, cannot switch to Text editing, Add Block button does not load anything.

**Expected behavior**
PPB was unaffected when running both SEO plugins prior to 5.0.1 and should continue to function properly.

**Comment by bwmarkle** [comment] 2018-12-19 14:17
Test comment on issue. Please disregard.

**Comment by rramo012** [comment] 2019-02-14 16:17
Duplicate of: https://github.com/BoldGrid/boldgrid-seo/issues/3

**Closed by rramo012** 2019-02-14 16:17 UTC
Labels: bug
