### ISSUE TITLE
[Feature] Better support for embedded videos

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/post-and-page-builder#175] opened 2021-04-02 15:51 UTC
**Is your feature request related to a problem? Please describe.**
Currently embedded video content does not behave responsively and custom CSS is required in order for videos to display properly across device sizes.

**Describe alternatives you've considered**
The solution used in support is to provide the following custom CSS to get video to resize properly:

```
.video-container {
	position:relative;
	padding-bottom:56.25%;
	padding-top:30px;
	height:0;
	overflow:hidden;
}

.video-container iframe, .video-container object, .video-container embed {
	position:absolute;
	top:0;
	left:0;
	width:100%;
	height:100%;
}
```
This also requires wrapping the iframe in a div with the `video-container` class.

**Comment by jessecowens** [comment] 2021-09-07 18:40
Duplicate of #184 closing this issue

**Closed by jessecowens** 2021-09-07 18:40 UTC
